---
- repeat: 1
  steps:
    - type: dataset
      name: face
      params:
        dir: ./data
        name: celeba50mp-normx
      out: orig
    - type: splitter
      name: withinlabel1to2
      params:
        rate: 0.8
      in: orig
      out: ["enroll", "test"]
    - type: privacy
      name: frknn
      params: {}
      in: ["enroll", "test"]
      out: results
    - type: metrics
      name: accuracy
      in: results
